# Generated by Django 3.0.2 on 2021-03-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_likebutton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButton',
        ),
    ]
