# Generated by Django 3.0.2 on 2021-03-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_isimagein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isImageIn',
        ),
    ]
