# Generated by Django 3.0.2 on 2021-03-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_isimagein'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isImageIn',
            field=models.BooleanField(default=False),
        ),
    ]
